# use docker-compose run coursera-dl
version: '3'
services: 
    coursera-dl:
        build:
            context: .
            dockerfile: MyDockerfile
        user: myuser
        working_dir: /home/myuser/coursera-dl
        tty: true
        volumes: 
            - ./transfer:/home/myuser/coursera-dl/transfer
            - /home/fan/CourseDump/Coursera:/home/myuser/dump
